# Require atleast 3 reviews
minApprovals:
  MEMBER: 3

# Update before merge
updateBranch: true

# Delete branch after merge
deleteBranchAfterMerge: true

# Merge method to use
mergeMethod: squash

# Message for the merge commmit
mergeCommitMessage: |
  (#{number}) {title}

  {body}

# Do not merge automatically into main
blockingBaseBranches:
  - main

# Merge automatically into develop, feature hotfix and release branches
requiredBaseBranches:
  - develop
  - regex: ^feature/
  - regex: ^release/
  - regex: ^hotfix/

# don't merge if tag is DONT_MERGE | WIP
blockingLabels:
  - DONT_MERGE
  - WIP
