blank_issues_enabled: false

contact_links:
  # TODO: add contact links
  # - name: Support channel
  #   url: 
  #   about: join our channel for any questions or discussions

  # TODO: add a link to the security issues reporting
  # - name: Security issues
  #   url:
  #   about: Please report security vulnerabilities here

  # TODO: add a link to the community forum
  # - name: Community Forum
  #   url:
  #   about: Ask questions and discuss with other community members
